services:
  redis:
    image: redis:7-alpine
    container_name: redis-chai-aur-code
    ports:
      - "6379:6379"
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:7
    container_name: mongodb-chai_aur_code
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDBBASE: chai_aur_code_redis
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  redis-data: